export const tempData1: any[] = [
    {
        category_groupName: '건물',
        category_name: '부동산 > 빌딩',
        place_name: '티맥스타워11',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.352644,
        x: 127.104032,
    },
    {
        category_groupName: '건물',
        category_name: '부동산 > 빌딩',
        place_name: '티맥스타워12',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.353644,
        x: 127.104032,
    },
    {
        category_groupName: '건물',
        category_name: '부동산 > 빌딩',
        place_name: '티맥스타워13',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.354644,
        x: 127.104032,
    },
    {
        category_groupName: '건물',
        category_name: '부동산 > 빌딩',
        place_name: '티맥스타워21',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.352644,
        x: 127.105032,
    },
    {
        category_groupName: '건물',
        category_name: '부동산 > 빌딩',
        place_name: '티맥스타워22',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.353644,
        x: 127.105032,
    },
    {
        category_groupName: '건물',
        category_name: '부동산 > 빌딩',
        place_name: '티맥스타워23',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.354644,
        x: 127.105032,
    },
    {
        category_groupName: '건물',
        category_name: '부동산 > 빌딩',
        place_name: '티맥스타워31',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.352644,
        x: 127.106032,
    },
    {
        category_groupName: '건물',
        category_name: '부동산 > 빌딩',
        place_name: '티맥스타워32',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.353644,
        x: 127.106032,
    },
    {
        category_groupName: '건물',
        category_name: '부동산 > 빌딩',
        place_name: '티맥스타워33',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.354644,
        x: 127.106032,
    },

];

export const tempData2: any[] = [
    {
        category_groupName: '전철',
        category_name: '분당선',
        place_name: '미금역11',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.349000,
        x: 127.110000,
    },
    {
        category_groupName: '전철',
        category_name: '분당선',
        place_name: '미금역12',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.349000,
        x: 127.109000,
    },
    {
        category_groupName: '전철',
        category_name: '분당선',
        place_name: '미금역13',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.349000,
        x: 127.108000,
    },
    {
        category_groupName: '전철',
        category_name: '분당선',
        place_name: '미금역21',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.350000,
        x: 127.110000,
    },
    {
        category_groupName: '전철',
        category_name: '분당선',
        place_name: '미금역22',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.350000,
        x: 127.109000,
    },
    {
        category_groupName: '전철',
        category_name: '분당선',
        place_name: '미금역23',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.350000,
        x: 127.108000,
    },
    {
        category_groupName: '전철',
        category_name: '분당선',
        place_name: '미금역31',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.351000,
        x: 127.110000,
    },
    {
        category_groupName: '전철',
        category_name: '분당선',
        place_name: '미금역32',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.351000,
        x: 127.109000,
    },
    {
        category_groupName: '전철',
        category_name: '분당선',
        place_name: '미금역33',
        phone: 'XXX-XXXX-XXXX',
        place_url: 'http://place.map.kakao.com/27121133',
        address_name: '경기 성남시 분당구 금곡동 196',
        road_address_name: '경기 성남시 분당구 정자일로 45',
        y: 37.351000,
        x: 127.108000,
    },

];